chore: add test and build workflows
Signed-off-by: Nam Hoang <hoangxuannam160493@gmail.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,59 +1,103 @@
 name: Release
 
 on:
-  push:
-    branches:
-      - main
-  workflow_dispatch:
+    push:
+        branches:
+            - main
+    workflow_dispatch:
 
 permissions:
-  contents: write
+    contents: write
 
 jobs:
-  release:
-    runs-on: ubuntu-latest
-    outputs:
-      new_version: ${{ steps.retrieve_version.outputs.new_version }}
+    test-and-build:
+        runs-on: ubuntu-latest
+        steps:
+            - uses: actions/checkout@v3
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+            - name: Install Node.js
+              uses: actions/setup-node@v3
+              with:
+                  node-version: '18'
+                  cache: 'yarn'
 
-      # Get the version from version.json file and store it in the output file
-      - name: Get version from version.json
-        id: retrieve_version
-        run: |
-          new_version=$(jq -r '.version' version.json)
-          if [ -z "$new_version" ]; then
-            echo "Error: version field is empty or not found in version.json!"
-            exit 1
-          fi
-          echo "new_version=$new_version" >> "$GITHUB_OUTPUT"
+            - name: Install dependencies
+              run: yarn install
 
-      # Create tag to the repository by using the version from the output file
-      - name: Create tag
-        id: create-tag
-        run: |
-          new_version=${{ steps.retrieve_version.outputs.new_version }}
+            - name: Check linting
+              run: yarn lint
 
-          git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git config --global user.name "github-actions[bot]"
-          git tag -a "$new_version" -m "Release version $new_version"
-          git push origin "$new_version"
+            - name: Run tests
+              run: yarn test
 
-          echo "new_tag=$new_version" >> "$GITHUB_OUTPUT"
+            - name: Build
+              run: yarn build
+    build_docs:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Checkout repository
+              uses: actions/checkout@v4
 
-      # Create GitHub release
-      - name: Create GitHub Release
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          new_version=${{ steps.retrieve_version.outputs.new_version }}
-          new_tag=${{ steps.create-tag.outputs.new_tag }}          
+            - name: Setup Node.js
+              uses: actions/setup-node@v3
+              with:
+                  node-version: 21
+                  cache: yarn
 
-          sed -n "/## \[$new_version\]/,/## \[/p" CHANGELOG.md | sed '$d' > release_notes.md
+            - name: Install and build documentation
+              run: |
+                  cd documentation
+                  yarn install --frozen-lockfile
+                  yarn build
+              env:
+                  DOCS_BASE_URL: ${{ vars.DOCS_BASE_URL }}
+                  DOCS_URL: ${{ vars.DOCS_URL }}
 
-          gh release create "$new_tag" \
-            --title "Release ${{ steps.retrieve_version.outputs.new_version }}" \
-            --notes-file release_notes.md \
-            --target ${{ github.ref_name }}
+    release:
+        needs: [test-and-build, build_docs]
+        runs-on: ubuntu-latest
+        outputs:
+            new_version: ${{ steps.retrieve_version.outputs.new_version }}
+
+        steps:
+            - name: Checkout code
+              uses: actions/checkout@v4
+
+            # Get the version from version.json file and store it in the output file
+            - name: Get version from version.json
+              id: retrieve_version
+              run: |
+                  new_version=$(jq -r '.version' version.json)
+                  if [ -z "$new_version" ]; then
+                    echo "Error: version field is empty or not found in version.json!"
+                    exit 1
+                  fi
+                  echo "new_version=$new_version" >> "$GITHUB_OUTPUT"
+
+            # Create tag to the repository by using the version from the output file
+            - name: Create tag
+              id: create-tag
+              run: |
+                  new_version=${{ steps.retrieve_version.outputs.new_version }}
+
+                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
+                  git config --global user.name "github-actions[bot]"
+                  git tag -a "$new_version" -m "Release version $new_version"
+                  git push origin "$new_version"
+
+                  echo "new_tag=$new_version" >> "$GITHUB_OUTPUT"
+
+            # Create GitHub release
+            - name: Create GitHub Release
+              env:
+                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+              run: |
+                  new_version=${{ steps.retrieve_version.outputs.new_version }}
+                  new_tag=${{ steps.create-tag.outputs.new_tag }}          
+
+                  sed -n "/## \[$new_version\]/,/## \[/p" CHANGELOG.md | sed '$d' > release_notes.md
+
+                  gh release create "$new_tag" \
+                    --title "Release ${{ steps.retrieve_version.outputs.new_version }}" \
+                    --notes-file release_notes.md \
+                    --target ${{ github.ref_name }}
